# Generated by Django 4.2.2 on 2023-07-16 08:19

import MyTvShows.tvshows.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes_watched', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[MyTvShows.tvshows.validators.check_name_capital_letter])),
                ('last_name', models.CharField(max_length=20, validators=[MyTvShows.tvshows.validators.check_name_capital_letter])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('day_of_airing', models.CharField(max_length=10)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tvshows.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('episodes', models.ManyToManyField(to='tvshows.episode')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tvshows.show')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tvshows.show')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Sci-fi', 'Sci-fi'), ('Drama', 'Drama'), ('Thriller', 'Thriller'), ('Animated', 'Animated')], default=None, max_length=20)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tvshows.show')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tvshows.show'),
        ),
    ]
