# Generated by Django 4.2.2 on 2023-07-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0006_category_thread_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
