# Generated by Django 4.2.2 on 2023-08-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0007_remove_thread_category_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeasonEpisodes',
        ),
    ]
