# Generated by Django 4.2.2 on 2023-08-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0009_episode_episode_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
    ]
