# Generated by Django 4.2.2 on 2023-08-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0010_remove_episode_description_remove_episode_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_number',
        ),
    ]
