# Generated by Django 4.2.2 on 2023-08-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0012_favouritetvshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritetvshow',
            name='Poster',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favouritetvshow',
            name='Title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favouritetvshow',
            name='Year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favouritetvshow',
            name='imdbID',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
