# Generated by Django 4.2.2 on 2023-08-16 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tvshows', '0014_tvshow_remove_favouritetvshow_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
