# Generated by Django 4.2.2 on 2023-08-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0015_tvshow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='user',
        ),
    ]
