# Generated by Django 4.2.2 on 2023-08-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0016_remove_tvshow_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('imdb_id', models.CharField(max_length=20)),
                ('poster', models.URLField()),
            ],
        ),
    ]
