# Generated by Django 4.2.2 on 2023-08-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0017_temporarysearchresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteTVShow',
        ),
    ]
