# Generated by Django 4.2.2 on 2023-08-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0018_delete_favouritetvshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarysearchresult',
            name='seasons',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='seasons',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
