# Generated by Django 4.2.2 on 2023-08-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0019_temporarysearchresult_seasons_tvshow_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarysearchresult',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='seasons',
        ),
        migrations.AddField(
            model_name='temporarysearchresult',
            name='num_episodes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporarysearchresult',
            name='num_seasons',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='num_episodes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='num_seasons',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
