# Generated by Django 4.2.2 on 2023-08-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0020_remove_temporarysearchresult_seasons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarysearchresult',
            old_name='num_episodes',
            new_name='seasons',
        ),
        migrations.RenameField(
            model_name='tvshow',
            old_name='num_episodes',
            new_name='seasons',
        ),
        migrations.RemoveField(
            model_name='temporarysearchresult',
            name='num_seasons',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='num_seasons',
        ),
    ]
