# Generated by Django 4.2.2 on 2023-08-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0022_temporarysearchresult_genre_tvshow_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarysearchresult',
            name='episodes_watched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='episodes_watched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
