# Generated by Django 4.2.2 on 2023-08-17 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tvshows', '0023_temporarysearchresult_episodes_watched_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='series',
        ),
        migrations.RemoveField(
            model_name='season',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='season',
            name='series',
        ),
        migrations.RemoveField(
            model_name='show',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='show',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='series',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
