# Generated by Django 4.2.2 on 2023-08-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0025_rename_imdb_id_temporarysearchresult_tvmaze_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarysearchresult',
            name='episodes',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='episodes',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
