# Generated by Django 4.2.2 on 2023-08-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0026_temporarysearchresult_episodes_tvshow_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarysearchresult',
            name='episodes',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='episodes',
            field=models.CharField(max_length=150),
        ),
    ]
