# Generated by Django 4.2.2 on 2023-08-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0027_alter_temporarysearchresult_episodes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tvshows.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tvshows.season')),
            ],
        ),
    ]
