# Generated by Django 4.2.2 on 2023-08-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0028_season_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='season_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
