# Generated by Django 4.2.2 on 2023-08-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0029_episode_episode_number_season_season_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tvshows.season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tvshows.tvshow'),
            preserve_default=False,
        ),
    ]
