# Generated by Django 4.2.2 on 2023-08-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0030_alter_episode_season_alter_season_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='num_episodes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
