# Generated by Django 4.2.2 on 2023-08-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0033_temporarysearchresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='show',
        ),
        migrations.RemoveField(
            model_name='temporarysearchresult',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='episodes',
        ),
        migrations.AlterField(
            model_name='temporarysearchresult',
            name='tvmaze_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
