# Generated by Django 4.2.2 on 2023-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0034_remove_season_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarysearchresult',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
