# Generated by Django 4.2.2 on 2023-08-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0035_temporarysearchresult_description_tvshow_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarysearchresult',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
